package views;

public enum Command {
    PROPIETARIOS, FINANZAS, CARTERA, MORA, AJUSTES, ADD_PERSON, EDIT_PERSON, REMOVE_PERSON, ADD_APARTMENT, EDIT_APARTMENT, REMOVE_APARTMENT, CREATE_PERSON, CANCEL_PERSON
}